name: Auto Post to Telegram

on:
  schedule:
    - cron: '*/2 * * * *'  # This runs every 2 minutes
  workflow_dispatch:  # Allows manual trigger from GitHub

jobs:
  send_message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Set the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyrogram tgcrypto

      - name: Run the script
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
        run: |
          python auto_post.py
