name: Telegram Bot Automation

on:
  workflow_dispatch:   # Allows manual triggering
  schedule:
    - cron: '0 * * * *'    # Every hour

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyrogram

      - name: Run Telegram Bot
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          MY_ACCOUNT_SESSION: ${{ secrets.MY_ACCOUNT_SESSION }}
        run: python posting.py
