name: Telegram Bot Automation

on:
  workflow_dispatch:   # Allows manual triggering
  schedule:
    # Schedule to run at each specific time in Malaysia Time (UTC+8)

    # PM Malaysia Times
    - cron: '59 4 * * *'   # 12:59 PM Malaysia time (UTC+8)
    - cron: '59 5 * * *'   # 1:59 PM Malaysia time (UTC+8)
    - cron: '59 6 * * *'   # 2:59 PM Malaysia time (UTC+8)
    - cron: '59 7 * * *'   # 3:59 PM Malaysia time (UTC+8)
    - cron: '59 8 * * *'   # 4:59 PM Malaysia time (UTC+8)
    - cron: '59 9 * * *'   # 5:59 PM Malaysia time (UTC+8)
    - cron: '59 10 * * *'  # 6:59 PM Malaysia time (UTC+8)
    - cron: '59 11 * * *'  # 7:59 PM Malaysia time (UTC+8)
    - cron: '59 12 * * *'  # 8:59 PM Malaysia time (UTC+8)
    - cron: '59 13 * * *'  # 9:59 PM Malaysia time (UTC+8)
    - cron: '59 14 * * *'  # 10:59 PM Malaysia time (UTC+8)
    - cron: '59 15 * * *'  # 11:59 PM Malaysia time (UTC+8)

    # AM Malaysia Times
    - cron: '59 16 * * *'  # 12:59 AM Malaysia time (UTC+8)
    - cron: '59 17 * * *'  # 1:59 AM Malaysia time (UTC+8)
    - cron: '59 18 * * *'  # 2:59 AM Malaysia time (UTC+8)
    - cron: '59 19 * * *'  # 3:59 AM Malaysia time (UTC+8)
    - cron: '59 20 * * *'  # 4:59 AM Malaysia time (UTC+8)
    - cron: '59 21 * * *'  # 5:59 AM Malaysia time (UTC+8)
    - cron: '59 22 * * *'  # 6:59 AM Malaysia time (UTC+8)
    - cron: '59 23 * * *'  # 7:59 AM Malaysia time (UTC+8)
    - cron: '59 0 * * *'   # 8:59 AM Malaysia time (UTC+8)
    - cron: '59 1 * * *'   # 9:59 AM Malaysia time (UTC+8)
    - cron: '59 2 * * *'   # 10:59 AM Malaysia time (UTC+8)
    - cron: '59 3 * * *'   # 11:59 AM Malaysia time (UTC+8)

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Ensure compatibility with your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyrogram tgcrypto

      - name: Run Telegram Bot
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          SESSION_STRING: ${{ secrets.SESSION_STRING }}
        run: python posting.py
