name: Telegram Bot Automation

on:
  workflow_dispatch:   # Allows manual triggering
  schedule:
    # Schedule to run every 4 hours in Malaysia Time (UTC+8)
    - cron: '0 0,4,8,12,16,20 * * *'  # 12:00 AM, 4:00 AM, 8:00 AM, 12:00 PM, 4:00 PM, 8:00 PM Malaysia time (UTC+8)

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Ensure compatibility with your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install telethon

      - name: Run Telegram Bot
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          SESSION_STRING: ${{ secrets.SESSION_STRING }}
        run: python posting.py
